spring:
  application:
    name: Hotel Management Service

  datasource:
    url: jdbc:mariadb://localhost:3306/my_hotel
    username: hotel_user
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false

server:
  port: 8081